site_name: Moxa IIoT Guide [Work in Progress]
site_url: https://guide.iiot.party
theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'teal'
  feature:
    tabs: true

repo_name: 'MOXA-ISD/iiot-guide'
repo_url: 'https://github.com/MOXA-ISD/iiot-guide'

nav:
- Home:
  - 'index.md'
- Get Started:
  - 'Overview': 'get-started/index.md'
  - 'Install on UC-8100 Series': 'get-started/uc-8100-series/index.md'
- Networking:
  - 'networking/index.md'
- Operations:
  - 'operations/index.md'
- Use Cases:
  - 'Overview': 'usecases/index.md'
  - Ignition Edge:
    - 'usecases/ignition/install/index.md'
    - 'usecases/ignition/tp-solar/index.md'
  - Azure IoT Edge:
    - 'usecases/iotedge/install.md'
- Development:
  - 'dev/index.md'
- Support:
  - 'support/index.md'
- About:
  - 'Audience': 'about/audience.md'
  - 'License': 'about/license.md'
  - 'How to contribute': 'about/how-to-contribute.md'

google_analytics:
  - 'UA-130485804-1'
  - 'auto'